language: go

go:
#  - 1.0 # works, but not supported by testify
#  - 1.1 # works, but doesn't do -coverprofile
  - 1.2
  - 1.3
  - tip

before_install:
  - go get github.com/stretchr/testify/require
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get code.google.com/p/go.tools/cmd/cover

script:
    - $HOME/gopath/bin/goveralls -repotoken $COVERALLS_TOKEN
